### ISSUE TITLE
Table 1. Private-sector companies that publish their data through GBIF (as of 7 August 2020)

### ISSUE THREAD

**Issue by dagendresen** [gbif/doc-private-sector-data-publishing#5]
DNV GL is missing from the table
https://www.gbif.org/publisher/efc5d3c7-2fec-42dd-85de-078a73973bd1
Dataset https://doi.org/10.15468/q8qykg 2,036,474 occurrences

**Comment by kcopas** [comment]
Sneaky—they're missing because we didn't know to add them! They were missing from the table the OpenPSD team provided in March because they only registered in April. In the absence of someone flagging publishers when they come in (more on that shortly), this will always require a heads-up.

Full table updated ahead of the video's launch—probably a good thing. Also, note that **all** of these publishers now have at least one citation. #CiteTheDOI
